--- 
title: "stream-analyses"
format: html
---


# Background 

Ion concentrations in Puerto Rico Streams before and after Hurricane Hugo.



# Data
Data is downloaded from: 
Data for each stream is seperated into different .csv files. 


```{r}
# load package 
library(tidyverse)
```

```{r}
prm <- read_csv("../data/knb-lter-luq/RioMameyesPuenteRoto.csv")
bq1 <- read_csv("../data/knb-lter-luq/QuebradaCuenca1-Bisley.csv")
bq2 <- read_csv("../data/knb-lter-luq/QuebradaCuenca2-Bisley.csv")
bq3 <- read_csv("../data/knb-lter-luq/QuebradaCuenca3-Bisley.csv")
```



```{r}
# clean the data 
prm_sub <- prm |> 
  filter(Sample_Date >= ymd("1988-01-01") & Sample_Date <= ymd("1994-12-31")) |> 
  select(Sample_ID, Sample_Date, K, `NO3-N`,`NH4-N`, Mg, Ca)

bq1_sub <- bq1 |> 
  filter(Sample_Date >= ymd("1988-01-01") & Sample_Date <= ymd("1994-12-31")) |> 
  select(Sample_ID, Sample_Date, K, `NO3-N`,`NH4-N`, Mg, Ca)

bq2_sub <- bq2 |> 
  filter(Sample_Date >= ymd("1988-01-01") & Sample_Date <= ymd("1994-12-31")) |> 
  select(Sample_ID, Sample_Date, K, `NO3-N`,`NH4-N`, Mg, Ca)

bq3_sub <- bq3 |> 
  filter(Sample_Date >= ymd("1988-01-01") & Sample_Date <= ymd("1994-12-31")) |> 
  select(Sample_ID, Sample_Date, K, `NO3-N`,`NH4-N`, Mg, Ca)
```

# Methods



# Results
